#!/bin/bash

#Disable startup sound
sudo systemctl disable startupsound.service
sudo systemctl daemon-reload

#Delete files
sudo rm -rf /etc/sound
sudo rm -rf /etc/systemd/system/startupsound.service
sudo rm -rf /bin/startupsound

#Done
echo "Done!"
